name: Update AoC Badges
on:
  workflow_dispatch:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: 1717876
          session: ${{ secrets.AOC_SESSION }}
          year: 2024
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022%20⭐-)[0-9]+(?=-yellow)'      

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: 1717876
          session: ${{ secrets.AOC_SESSION }}
          year: 2023
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022%20⭐-)[0-9]+(?=-yellow)'

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: 1717876
          session: ${{ secrets.AOC_SESSION }}
          year: 2022
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022%20⭐-)[0-9]+(?=-yellow)'

      - uses: J0B10/aoc-badges-action@v3.0.0
        with:
          userid: 1717876
          session: ${{ secrets.AOC_SESSION }}
          year: 2021
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021%20⭐-)[0-9]+(?=-yellow)'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md